spring.application.name=gateway
server.port=${SERVER_PORT:8084}

deal.base-url=${DEAL_SERVER_URL:http://deal:8082/deal}
deal.service-loan-offers=/statement
deal.service-select-offer=/offer/select
deal.service-finish-registration=/calculate/{statementId}
deal.service-send-documents=/document/{statementId}/send
deal.service-sign-documents=/document/{statementId}/sign
deal.service-confirm-code=/document/{statementId}/code
deal.admin-service-url=${DEAL_SERVER_URL:http://localhost:8082/deal/admin}
deal.admin-service-get-statement-by-id=/admin/statement/{statementId}
deal.admin-service-get-all-statements=admin/statement

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://database:5433/deal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5117}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect